# Areas

areas_list = [
	'Coordinating and Organising',
	'Planning',
	'Functional Management',
	'Operational Management',
	'Auditing',
	'External Communication',
	'Management Communication',
	'Operational Communication',
	'Finance',
	'General Technology',
	'Specialist Technology',
	'Design and Innovation',
	'People Development',
	'People Management',
	'Leadership'
]

areas_list.each do |name|
  Area.create( name: name )
end

# Activities

activity_list = [
	['Coordinating activities between functions', 96, 1, 'Coordinating and Organising'],
	['Coordinating activity of supervisors', 50, 1, 'Coordinating and Organising'],
	['Coordinating managers / departments', 38, 1, 'Coordinating and Organising'],
	['Coordinating your staff / team and their work', 5, 1, 'Coordinating and Organising'],
	['Organising external events', 99, 1, 'Coordinating and Organising'],
	['Organising general meetings', 39, 1, 'Coordinating and Organising'],
	['Organising internal events', 55, 1, 'Coordinating and Organising'],
	['Organising management meetings', 66, 1, 'Coordinating and Organising'],
	['Organising staff meetings', 54, 1, 'Coordinating and Organising'],
	['Organising yourself and your work', 43, 1, 'Coordinating and Organising'],
	['Business planning (longer-term)', 61, 2, 'Planning'],
	['Functional / departmental planning', 12, 2, 'Planning'],
	['Operational planning', 82, 2, 'Planning'],
	['Planning presentations (sales / technical / PR)', 47, 2, 'Planning'],
	['General project management', 40, 3, 'Functional Management'],
	['Managing customers / customer relationships', 94, 3, 'Functional Management'],
	['Managing environmental processes', 101, 3, 'Functional Management'],
	['Managing finance / budgeting', 31, 3, 'Functional Management'],
	['Managing health and safety', 7, 3, 'Functional Management'],
	['Managing ICT', 44, 3, 'Functional Management'],
	['Managing logistics', 45, 3, 'Functional Management'],
	['Managing personnel / human resources', 1, 3, 'Functional Management'],
	['Managing procurement', 15, 3, 'Functional Management'],
	['Managing recruitment / selection', 19, 3, 'Functional Management'],
	['Managing research and development', 92, 3, 'Functional Management'],
	['Managing sales / marketing', 97, 3, 'Functional Management'],
	['Managing / supervising a team', 23, 4, 'Operational Management'],
	['Managing / supervising individuals', 25, 4, 'Operational Management'],
	['Managing other managers', 58, 4, 'Operational Management'],
	['Managing quality / improvement', 70, 4, 'Operational Management'],
	['Managing supervisors', 59, 4, 'Operational Management'],
	['Auditing quality systems', 88, 5, 'Auditing'],
	['Auditing environmental processes', 26, 5, 'Auditing'],
	['Auditing health and safety', 77, 5, 'Auditing'],
	['Communicating / negotiating with customers', 65, 6, 'External Communication'],
	['Communicating / negotiating with suppliers', 6, 6, 'External Communication'],
	['Giving external presentations', 52, 6, 'External Communication'],
	['Public relations', 42, 6, 'External Communication'],
	['Selling products / services', 95, 6, 'External Communication'],
	['Communicating between teams', 102, 7, 'Management Communication'],
	['Communicating targets and performance', 46, 7, 'Management Communication'],
	['Leading management meeting / briefings', 72, 7, 'Management Communication'],
	['Providing internal specialist advisory services', 24, 7, 'Management Communication'],
	['Team working skills', 80, 7, 'Management Communication'],
	['Collating, analysing and disseminating information', 84, 8, 'Operational Communication'],
	['Communicating to, and within, teams', 22, 8, 'Operational Communication'],
	['Email communication (essential to role)', 2, 8, 'Operational Communication'],
	['Giving internal presentations', 21, 8, 'Operational Communication'],
	['Leading staff meetings / briefings', 91, 8, 'Operational Communication'],
	['Negotiating internally', 78, 8, 'Operational Communication'],
	['Sharing information and ideas with colleagues', 28, 8, 'Operational Communication'],
	['Telephone communication (essential to role)', 16, 8, 'Operational Communication'],
	['Bookkeeping', 30, 9, 'Finance'],
	['Interpreting / reporting on financial information', 74, 9, 'Finance'],
	['Management accounts', 49, 9, 'Finance'],
	['Financial monitoring and accounts', 36, 9, 'Finance'],
	['Setting / monitoring departmental budget(s)', 87, 9, 'Finance'],
	['Setting / monitoring section budget', 10, 9, 'Finance'],
	['Using database software', 90, 10, 'General Technology'],
	['Using email software (e.g. Outlook)', 56, 10, 'General Technology'],
	['Using in-house software (e.g. a CRM)', 41, 10, 'General Technology'],
	['Using presentation software (e.g. PowerPoint)', 27, 10, 'General Technology'],
	['Using social media for the organisation', 35, 10, 'General Technology'],
	['Using spreadsheet software (e.g. Excel)', 68, 10, 'General Technology'],
	['Using the Internet', 11, 10, 'General Technology'],
	['Using word processing software (e.g. Word)', 93, 10, 'General Technology'],
	['Maintaining websites', 63, 11, 'Specialist Technology'],
	['Managing and maintaining ICT hardware', 18, 11, 'Specialist Technology'],
	['Managing and maintaining ICT software', 89, 11, 'Specialist Technology'],
	['Using specialist software', 48, 11, 'Specialist Technology'],
	['Creative design', 14, 12, 'Design and Innovation'],
	['Image design (for marketing)', 76, 12, 'Design and Innovation'],
	['Introducing new technology', 69, 12, 'Design and Innovation'],
	['Developing new products', 13, 12, 'Design and Innovation'],
	['Developing new services', 64, 12, 'Design and Innovation'],
	['Coaching / mentoring others', 51, 13, 'People Development'],
	['Conducting appraisals (or similar)', 100, 13, 'People Development'],
	['Developing supervisors / managers', 9, 13, 'People Development'],
	['Motivating others', 60, 13, 'People Development'],
	['Talent-spotting', 33, 13, 'People Development'],
	['Team building skills', 4, 13, 'People Development'],
	['Training others', 62, 13, 'People Development'],
	['Deploying / redeploying staff', 83, 14, 'People Management'],
	['Deploying / redeploying managers', 67, 14, 'People Management'],
	['Disciplining others', 3, 14, 'People Management'],
	['Managing change and continuous improvement', 85, 14, 'People Management'],
	['Managing productivity', 53, 14, 'People Management'],
	['Managing the time of others productively', 57, 14, 'People Management'],
	['Managing your own time effectively', 32, 14, 'People Management'],
	['Monitoring performance', 79, 14, 'People Management'],
	['Progress reporting', 98, 14, 'People Management'],
	['Setting targets / key performance indicators', 8, 14, 'People Management'],
	['Work allocation', 71, 14, 'People Management'],
	['Defining / redefining policies', 81, 15, 'Leadership'],
	['Defining management roles and responsibilities', 34, 15, 'Leadership'],
	['Developing new processes', 29, 15, 'Leadership'],
	['Developing new systems', 75, 15, 'Leadership'],
	['Leading financial strategy', 17, 15, 'Leadership'],
	['Leading whole organisation purpose / vision', 37, 15, 'Leadership'],
	['Leading quality / improvement strategy', 20, 15, 'Leadership'],
	['Leading innovation', 86, 15, 'Leadership'],
	['Strategic planning', 73, 15, 'Leadership']
]

activity_list.each do |name, order_id, area_id, area_name|
	Activity.create( name: name, order_id: order_id, area_id: area_id, area_name: area_name )
end